When creating new QualifiedName with method [Namespace#newQualifiedName()](https://github.com/lucmoreau/ProvToolbox/blob/ca05849c88a84aae736355569a8bdae78c68b072/modules-core/prov-model/src/main/java/org/openprovenance/prov/model/Namespace.java#L271), there is no validation in [constructor of QualifiedName](https://github.com/lucmoreau/ProvToolbox/blob/ca05849c88a84aae736355569a8bdae78c68b072/modules-core/prov-model/src/main/java/org/openprovenance/prov/vanilla/QualifiedName.java#L15) and also when creating a new entity with method [ProvFactory#newEntity()](https://github.com/lucmoreau/ProvToolbox/blob/ca05849c88a84aae736355569a8bdae78c68b072/modules-core/prov-model/src/main/java/org/openprovenance/prov/vanilla/ProvFactory.java#L166) and setting identifier in [Entity constructor](https://github.com/lucmoreau/ProvToolbox/blob/ca05849c88a84aae736355569a8bdae78c68b072/modules-core/prov-model/src/main/java/org/openprovenance/prov/vanilla/Entity.java#L31), there is no validation.
This means that we can create invalid identifiers in ProvToolbox.

When serializing PROV-XML format, the identifier is not validated.
However, this is not wrong since the serializer should not expect ProvToolbox to generate a PROV document with an invalid QualifiedName. The problem arises in the model where an invalid QualifiedName can be generated.

When deserializing from PROV-XML, Prov Python uses custom [ProvXMLSerializer](https://github.com/trungdong/prov/blob/master/src/prov/serializers/provxml.py#L34).
When deserializing it uses the [ProvXMLSerializer#deserialize()](https://github.com/trungdong/prov/blob/1cb710a26c623c5c706b1c6945c645efd9e925c0/src/prov/serializers/provxml.py#L218) method, which on line 229 uses [etree](https://lxml.de/tutorial.html) from [lxml](https://lxml.de/) library to obtain the etree Element object like this:

\`xml_doc = etree.parse(buf).getroot()\`

After that, on line 239, it uses the [ProvXMLSerializer#deserialize_subtree()](https://github.com/trungdong/prov/blob/master/src/prov/serializers/provxml.py#L242) method, which fills the ProvDocument it gets passed in arguments from the etree Element object.

\`self.deserialize_subtree(xml_doc, document)\`

When converting the identifier \`ex:a b c\` from XML Qname to QualifiedName, Prov Python uses function [xml_qname_to_QualifiedName()](https://github.com/trungdong/prov/blob/1cb710a26c623c5c706b1c6945c645efd9e925c0/src/prov/serializers/provxml.py#L362). In this function no validation of identifier is done. 

Therefore, Prov Python creates a document with an invalid identifier.